var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){a!=Array.prototype&&a!=Object.prototype&&(a[b]=d.value)};
$jscomp.polyfill=function(a,b,d,e){if(b){d=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var c=a[e];c in d||(d[c]={});d=d[c]}a=a[a.length-1];e=d[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function d(a){return a instanceof c?a:new c(function(b,r){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};b.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var e=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){e(a,
0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];a[b]=null;try{c()}catch(f){this.asyncThrow_(f)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var c=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(l){b.reject(l)}};c.prototype.createResolveAndReject_=
function(){function a(a){return function(r){c||(c=!0,a.call(b,r))}}var b=this,c=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};c.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof c)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};c.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(l){this.reject_(l);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};c.prototype.reject_=function(a){this.settle_(2,a)};c.prototype.fulfill_=function(a){this.settle_(1,a)};c.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};c.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
0;a<this.onSettledCallbacks_.length;++a)k.asyncExecute(this.onSettledCallbacks_[a]);this.onSettledCallbacks_=null}};var k=new b;c.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};c.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(f){c.reject(f)}};c.prototype.then=function(a,b){function d(a,b){return"function"==typeof a?function(b){try{f(a(b))}catch(n){e(n)}}:
b}var f,e,g=new c(function(a,b){f=a;e=b});this.callWhenSettled_(d(a,f),d(b,e));return g};c.prototype.catch=function(a){return this.then(void 0,a)};c.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?k.asyncExecute(c):this.onSettledCallbacks_.push(c)};c.resolve=d;c.reject=function(a){return new c(function(b,c){c(a)})};c.race=function(a){return new c(function(b,
c){for(var e=$jscomp.makeIterator(a),h=e.next();!h.done;h=e.next())d(h.value).callWhenSettled_(b,c)})};c.all=function(a){var b=$jscomp.makeIterator(a),e=b.next();return e.done?d([]):new c(function(a,c){function f(b){return function(c){h[b]=c;k--;0==k&&a(h)}}var h=[],k=0;do h.push(void 0),k++,d(e.value).callWhenSettled_(f(h.length-1),c),e=b.next();while(!e.done)})};return c},"es6","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(d){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){a=$jscomp.makeIterator(a);var d=a.next();$jscomp.generator.ensureIteratorResultIsObject_(d);if(d.done)this.yieldResult=d.value,this.nextAddress=b;else return this.yieldAllIterator_=a,this.yield(d.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,d){d?this.finallyContexts_[d]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();void 0!=b.jumpTo&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(a){return{value:a,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,d){try{var e=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(e);if(!e.done)return this.context_.stop_(),e;var c=e.value}catch(k){return this.context_.yieldAllIterator_=null,this.context_.throw_(k),this.nextStep_()}this.context_.yieldAllIterator_=null;d.call(this.context_,c);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){b=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&$jscomp.setPrototypeOf(b,a.prototype);return b};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(b){return a.next(b)}function d(b){return a.throw(b)}return new Promise(function(e,c){function k(a){a.done?e(a.value):Promise.resolve(a.value).then(b,d).then(k,c)}k(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
(function(){function a(a,b){return cryptocurrency_prices.Gen.DoesFuncExist("Intl.NumberFormat")?(new Intl.NumberFormat({},{maximumFractionDigits:2})).format(a):a.toFixed(2)}function b(a){return{coinMarketCap:{requestUrl:cryptocurrency_prices.Net.UpdateQueryArgs("https://api.coinmarketcap.com/v2/ticker/",{limit:a.itemsMax}),getItems:function(b){var c,e,d,g,l;return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){c=b.data;if(!c)return f.return(null);b=[];e=0;for(d in c)if(g=c[d],l={name:g.name,
symbol:g.symbol,slug:g.website_slug,rank:g.rank,iconUrl:"https://s2.coinmarketcap.com/static/img/coins/16x16/"+g.id+".png",graphContent:cryptocurrency_prices.Ui.Tag("img",null,{src:"https://s2.coinmarketcap.com/generated/sparklines/web/7d/usd/"+g.id+".png"},!0),quotes:{USD:{percentChange24h:g.quotes.USD.percent_change_24h,price:g.quotes.USD.price,marketCap:g.quotes.USD.market_cap}}},b.push(l),e++,e==a.itemsMax)break;return f.return(b)})}},coinCapIo:{requestUrl:cryptocurrency_prices.Net.UpdateQueryArgs("https://api.coincap.io/v2/assets",
{limit:a.itemsMax}),getItems:function(b){var c,d,e,g,l,f,h,q,p,m,t;return $jscomp.asyncExecutePromiseGeneratorProgram(function(k){switch(k.nextAddress){case 1:c=b.data;if(!c)return k.return(null);d=(new Date).getTime();e=d-6048E5;b=[];g=0;l=Math.min(c.length,a.itemsMax);case 2:if(!(g<l)){k.jumpTo(4);break}f=c[g];return k.yield(jQuery.ajax({url:cryptocurrency_prices.Net.UpdateQueryArgs("https://api.coincap.io/v2/assets/"+f.id+"/history",{interval:"h6",start:e,end:d})}),5);case 5:if(h=k.yieldResult){h=
h.data;q=[];for(p=0;p<h.length;p++)q.push(h[p].priceUsd);h=q}else h=[];h.push(f.priceUsd);m=parseFloat(h[h.length-1])>parseFloat(h[0]);t={name:f.name,symbol:f.symbol,slug:f.id,rank:f.rank,iconUrl:"https://static.coincap.io/assets/icons/"+f.symbol.toLowerCase()+"@2x.png",graphContent:cryptocurrency_prices.Ui.Tag("div",cryptocurrency_prices.Ui.Tag("canvas",null,{"data-bg-color":m?"#90EE90":"#ff9999","data-color":m?"#006400":"#ff0000",width:164,height:48,"class":["sparkline-charts","chartjs-render-monitor1"],
style:{display:"block",height:"100%",width:"100%"},"data-content":JSON.stringify(h)},{"class":m?"up":"down"})),quotes:{USD:{percentChange24h:f.changePercent24Hr,price:f.priceUsd,marketCap:f.marketCapUsd}}};b.push(t);g++;k.jumpTo(2);break;case 4:return k.return(b)}})}}}}cryptocurrency_prices.App={GetContent:function(d,e){var c=b(e)[d];return new Promise(function(b,d){c?jQuery.ajax({url:c.requestUrl,dataType:"json",cache:!1}).then(function(d){c.getItems(d).then(function(c){if(c){var d='<table style="font-size:'+
e.fontScale+'em;">';d+='<thead><th style="text-align:center;">Coin</th><th style="text-align:center;">Price</th><th style="white-space:nowrap;text-align:center;">Market Cap</th><th style="white-space:nowrap;text-align:center;">24HR +-</th><th style="white-space:nowrap;text-align:center;">7D</th></thead><tbody>';for(var h=0,k=c.length;h<k;h++){var g=c[h],m=g.quotes.USD,l=m.percentChange24h,n=e.coinsLinksTpl;n=cryptocurrency_prices.Gen.StrReplaceAll(n,"{symbol}",g.symbol);n=cryptocurrency_prices.Gen.StrReplaceAll(n,
"{slug}",g.slug);d+="<tr>";d+='<td class="name" style="white-space:nowrap;text-align:center;"><img width=16 height=16 style="vertical-align:middle;margin-right:0.4em;" src="'+g.iconUrl+'" />';d+=cryptocurrency_prices.Ui.Link(g.symbol,e.showCoinsLinks?n:null,!0);d+="</td>";d+='<td class="price" style="white-space:nowrap;text-align:center;">$'+a(m.price,2)+"</td>";d+='<td class="market_cap" style="white-space:nowrap;text-align:center;">$'+a(m.marketCap/1E9,2)+" B</td>";d+='<td class="percent_change_24h'+
(0<l?" inc":0>l?" dec":"")+'" style="white-space:nowrap;text-align:center;">'+a(l,2)+"%</td>";d+=cryptocurrency_prices.Ui.Tag("td",g.graphContent,{"class":"price_graph_7d",style:{"white-space":"nowrap",width:"10%"}});d+="</tr>"}b(d+"</tbody></table>")}else b("")},function(){b("")})},function(a){b("")}):b("")})},GenerateSmallChart:function(a,b){a=jQuery(a);var c=a.data("color"),d=a.data("bg-color"),e=b.isChartFill,g=b.currencyPrice,l=b.currency;b=b.currencySymbol;var f=a.data("content");f&&("BTC"!=
l&&(f=f.map(function(a){a=parseFloat(a)*g;return a.toFixed(1<=a?2:1E-6>a?8:6)})),function(a,b,c,d,e,f,g){var h=a.get(0).getContext("2d"),k="#ff0000"==c?"#f5c992":"#006400"==c?"#5cdfbb":c,l="#ff9999"==d?"#f7e0c3":"#90EE90"==d?"#c1ffee":d,m=h.createLinearGradient(0,0,a.prop("width"),0);m.addColorStop(0,k);m.addColorStop(1,c);c=h.createLinearGradient(0,0,a.prop("height"),0);c.addColorStop(0,l);c.addColorStop(1,d);d={labels:b,datasets:[{fill:e,lineTension:.25,borderWidth:1.5,pointRadius:f,data:b,backgroundColor:c,
borderColor:m,pointBorderColor:m}]};e=Math.max.apply(Math,b)+1*Math.max.apply(Math,b)/100;b=Math.min.apply(Math,b)-1*Math.min.apply(Math,b)/100;new Chart(a,{type:"line",data:d,options:{hover:{mode:"nearest",intersect:!0},responsive:!1,maintainAspectRatio:!1,scales:{xAxes:[{display:!1}],yAxes:[{display:!1,ticks:{min:b,max:e}}]},animation:{duration:400},legend:{display:!1},tooltips:{mode:"index",intersect:!1,displayColors:!1,callbacks:{label:function(a,b){b=parseFloat(a.xLabel);a=isNaN(b)?"-":(b=(b+
"").split("."))[0].replace(/(\d{1,3})(?=(?:\d{3})+(?!\d))/g,"$1,")+(1<b.length?"."+b[1]:"");return g+" "+a},title:function(a,b){return!1}}}}})}(a,f,c,d,e,0,b))}};cryptocurrency_prices.App._int={apiUri:""}})();
