var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(c,l,f){if(null==c)throw new TypeError("The 'this' value for String.prototype."+f+" must not be null or undefined");if(l instanceof RegExp)throw new TypeError("First argument to String.prototype."+f+" must not be a regular expression");return c+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,l,f){c!=Array.prototype&&c!=Object.prototype&&(c[l]=f.value)};$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(c,l,f,a){if(l){f=$jscomp.global;c=c.split(".");for(a=0;a<c.length-1;a++){var b=c[a];b in f||(f[b]={});f=f[b]}c=c[c.length-1];a=f[c];l=l(a);l!=a&&null!=l&&$jscomp.defineProperty(f,c,{configurable:!0,writable:!0,value:l})}};
$jscomp.polyfill("String.prototype.repeat",function(c){return c?c:function(c){var f=$jscomp.checkStringArgs(this,null,"repeat");if(0>c||1342177279<c)throw new RangeError("Invalid count value");c|=0;for(var a="";c;)if(c&1&&(a+=f),c>>>=1)f+=f;return a}},"es6","es3");
(function(){function c(a,b,d){if("string"===typeof b)return a.indexOf(b,d);if(!Array.isArray(b))return-1;var k=-1;for(c in b){var c=b[c];var f=a.indexOf(c,d);-1!=f&&(-1==k||k>f)&&(k=f)}return k}function l(a,b,d){if("string"===typeof b)return a.lastIndexOf(b,d);if(!Array.isArray(b))return-1;var k=-1;for(c in b){var c=b[c];var f=a.lastIndexOf(c,d);-1!=f&&(-1==k||k<f)&&(k=f)}return k}function f(a){if(!a||"object"!==typeof a)return a;var b=Array===a.constructor?[]:{};for(var d in a)b[d]=f(a[d]);return b}
cryptocurrency_prices.Gen={DoesFuncExist:function(a){return!!a.split(".").reduce(function(a,d){return"undefined"==typeof a?a:a[d]},window)},ParseCmdline:function(a,b){b=void 0===b?!0:b;var d=[];if("string"!=typeof a)return d;a=a.trim();for(var k=a.length,c=!1,f="",l=0;l<k;l++)" "!==a.charAt(l)||c?'"'===a.charAt(l)&&b?c=!c:f+=a.charAt(l):(d.push(f),f="");d.push(f);return d},GetFileName:function(a,b){b=void 0===b?!1:b;a=a.split("\\").pop().split("/").pop();b&&(b=a.lastIndexOf("."),-1!=b&&(a=a.substr(0,
b)));return a},GetFileDir:function(a,b,d){b=void 0===b?!1:b;d=void 0===d?1:d;if(!d)return a;if(0<d)for(;;){var k=l(a,["/","\\"],k);if(-1==k||0==k)break;d--;if(!d)break;k--}else for(d*=-1;;){k=c(a,["/","\\"],k);if(-1==k)break;d--;if(!d)break;k++}return-1==k?"":a.substr(0,k+(b?1:0))},GetFileExt:function(a,b){b=void 0===b?!1:b;var d=a.lastIndexOf(".");return-1==d?"":a.substr(d+(b?0:1))},SetLastSlash:function(a,b,d){b=void 0===b?!0:b;d=void 0===d?"/":d;if("string"!==typeof a||!a.length)return"";if(a.lastIndexOf(d)==
a.length-1){if(!b)return a.substr(0,a.length-1)}else if(b)return a+d;return a},SetFirstSlash:function(a,b,d){b=void 0===b?!0:b;d=void 0===d?"/":d;if("string"!==typeof a||!a.length)return"";if(0==a.indexOf(d)){if(!b)return a.substr(1)}else if(b)return d+a;return a},StrReplaceAll:function(a,b,d){for(var c=0;;){c=a.indexOf(b,c);if(-1==c)break;a=a.substr(0,c)+d+a.substr(c+b.length);c+=d.length}return a},StrIndexOf:c,StrLastIndexOf:l,FilterObjectKeys:function(a,b,d){b=void 0===b?null:b;d=void 0===d?null:
d;var c={},f;for(f in a)d&&-1!==d.indexOf(f)||b&&-1===b.indexOf(f)||(c[f]=a[f]);return c},DeepCopy:f};cryptocurrency_prices.Wp={Loc:{GetApi:function(){var a=null;a=wp&&wp.i18n?wp.i18n:{__:function(a,d){return cryptocurrency_prices.Wp.Loc._int.dcnpgettext(d,void 0,a)},_x:function(a,d,c){return cryptocurrency_prices.Wp.Loc._int.dcnpgettext(c,d,a)},_n:function(a,d,c,f){return cryptocurrency_prices.Wp.Loc._int.dcnpgettext(f,void 0,a,d,c)},_nx:function(a,d,c,f,l){return cryptocurrency_prices.Wp.Loc._int.dcnpgettext(l,
f,a,d,c)},sprintf:cryptocurrency_prices.Wp.Loc._int.sprintf};a.vsprintf||(a.vsprintf=function(b,d){return a.sprintf.apply(null,[b].concat(d||[]))});return a},SetData:function(a,b){return wp&&wp.i18n?wp.i18n.setLocaleData(a,b):cryptocurrency_prices.Wp.Loc._int.setLocaleData(a,b)}}};(function(){function a(a){for(var b=[],c=[],d,h,e;d=a.match(w);){h=d[0];for((e=a.substr(0,d.index).trim())&&b.push(e);e=c.pop();){if(p[h]){if(p[h][0]===e){h=p[h][1]||h;break}}else if(0<=v.indexOf(e)||l[e]<l[h]){c.push(e);
break}b.push(e)}p[h]||c.push(h);a=a.substr(d.index+h.length)}(a=a.trim())&&b.push(a);return b.concat(c.reverse())}function b(b){var c=a(b);return function(a){a:{var b=[],d,e;for(d=0;d<c.length;d++){var h=c[d];if(e=x[h])try{var u=e.apply(null,b.splice(-1*e.length))}catch(g){a=g;break a}else u=a.hasOwnProperty(h)?a[h]:+h;b.push(u)}a=b[0]}return a}}function d(a){var c=b(a);return function(a){return+c({n:a})}}function c(a){var b=a;if(t[b])b=t[b];else{for(var d=b,h,f=[],e=0;d;){if(null!==(h=m.text.exec(d)))f.push(h[0]);
else if(null!==(h=m.modulo.exec(d)))f.push("%");else if(null!==(h=m.placeholder.exec(d))){if(h[2]){e|=1;var l=[],k=h[2],g;if(null!==(g=m.key.exec(k)))for(l.push(g[1]);""!==(k=k.substring(g[0].length));)if(null!==(g=m.key_access.exec(k)))l.push(g[1]);else if(null!==(g=m.index_access.exec(k)))l.push(g[1]);else throw new SyntaxError("[sprintf] failed to parse named argument key");else throw new SyntaxError("[sprintf] failed to parse named argument key");h[2]=l}else e|=2;if(3===e)throw Error("[sprintf] mixing positional and named placeholders is not (yet) supported");
f.push({placeholder:h[0],param_no:h[1],keys:h[2],sign:h[3],pad_char:h[4],align:h[5],width:h[6],precision:h[7],type:h[8]})}else throw new SyntaxError("[sprintf] unexpected placeholder");d=d.substring(h[0].length)}b=t[b]=f}d=arguments;h=1;f=b.length;l="";var n,p;for(k=0;k<f;k++)if("string"===typeof b[k])l+=b[k];else if("object"===typeof b[k]){g=b[k];if(g.keys)for(e=d[h],n=0;n<g.keys.length;n++){if(void 0==e)throw Error(c('[sprintf] Cannot access property "%s" of undefined value "%s"',g.keys[n],g.keys[n-
1]));e=e[g.keys[n]]}else e=g.param_no?d[g.param_no]:d[h++];m.not_type.test(g.type)&&m.not_primitive.test(g.type)&&e instanceof Function&&(e=e());if(m.numeric_arg.test(g.type)&&"number"!==typeof e&&isNaN(e))throw new TypeError(c("[sprintf] expecting number but found %T",e));m.number.test(g.type)&&(p=0<=e);switch(g.type){case "b":e=parseInt(e,10).toString(2);break;case "c":e=String.fromCharCode(parseInt(e,10));break;case "d":case "i":e=parseInt(e,10);break;case "j":e=JSON.stringify(e,null,g.width?parseInt(g.width):
0);break;case "e":e=g.precision?parseFloat(e).toExponential(g.precision):parseFloat(e).toExponential();break;case "f":e=g.precision?parseFloat(e).toFixed(g.precision):parseFloat(e);break;case "g":e=g.precision?String(Number(e.toPrecision(g.precision))):parseFloat(e);break;case "o":e=(parseInt(e,10)>>>0).toString(8);break;case "s":e=String(e);e=g.precision?e.substring(0,g.precision):e;break;case "t":e=String(!!e);e=g.precision?e.substring(0,g.precision):e;break;case "T":e=Object.prototype.toString.call(e).slice(8,
-1).toLowerCase();e=g.precision?e.substring(0,g.precision):e;break;case "u":e=parseInt(e,10)>>>0;break;case "v":e=e.valueOf();e=g.precision?e.substring(0,g.precision):e;break;case "x":e=(parseInt(e,10)>>>0).toString(16);break;case "X":e=(parseInt(e,10)>>>0).toString(16).toUpperCase()}if(m.json.test(g.type))l+=e;else{if(!m.number.test(g.type)||p&&!g.sign)var r="";else r=p?"+":"-",e=e.toString().replace(m.sign,"");n=g.pad_char?"0"===g.pad_char?"0":g.pad_char.charAt(1):" ";var q=g.width-(r+e).length;
q=g.width?0<q?n.repeat(q):"":"";l+=g.align?r+e+q:"0"===n?r+q+e:q+r+e}}return l}cryptocurrency_prices.Wp.Loc._int={data:{},pluralForms:{},options:{contextDelimiter:"\u0004"},setLocaleData:function(a,b){a||(a=f);var d=this.data[b];if(d)for(var h in d)a[h]=d[h];this.data[b]=a},dcnpgettext:function(a,b,d,c,f){this.data[a]||this.setLocaleData(void 0,a);f=void 0===f?0:this.getPluralForm(a,f);var e=d;b&&(e=b+this.options.contextDelimiter+d);return(a=this.data[a][e])&&a[f]?a[f]:0===f?d:c},getPluralForm:function(a,
b){var c=this.pluralForms[a];if(!c){c=this.data[a][""];a:{var h;c=(c["Plural-Forms"]||c["plural-forms"]||c.plural_forms).split(";");for(h=0;h<c.length;h++){var f=c[h].trim();if(0===f.indexOf("plural=")){c=f.substr(7);break a}}c=void 0}c=this.pluralForms[a]=d(c)}return c(b)},sprintf:c};var f={"":{plural_forms:"plural=(n!=1)"}};var l={"(":9,"!":8,"*":7,"/":7,"%":7,"+":6,"-":6,"<":5,"<=":5,">":5,">=":5,"==":4,"!=":4,"&&":3,"||":2,"?":1,"?:":1};var v=["(","?"];var p={")":["("],":":["?","?:"]};var w=/<=|>=|==|!=|&&|\|\||\?:|\(|!|\*|\/|%|\+|-|<|>|\?|\)|:/;
var x={"!":function(a){return!a},"*":function(a,b){return a*b},"/":function(a,b){return a/b},"%":function(a,b){return a%b},"+":function(a,b){return a+b},"-":function(a,b){return a-b},"<":function(a,b){return a<b},"<=":function(a,b){return a<=b},">":function(a,b){return a>b},">=":function(a,b){return a>=b},"==":function(a,b){return a===b},"!=":function(a,b){return a!==b},"&&":function(a,b){return a&&b},"||":function(a,b){return a||b},"?:":function(a,b,c){if(a)throw b;return c}},m={not_string:/[^s]/,
not_bool:/[^t]/,not_type:/[^T]/,not_primitive:/[^v]/,number:/[diefg]/,numeric_arg:/[bcdiefguxX]/,json:/[j]/,not_json:/[^j]/,text:/^[^\x25]+/,modulo:/^\x25{2}/,placeholder:/^\x25(?:([1-9]\d*)\$|\(([^)]+)\))?(\+)?(0|'[^$])?(-)?(\d+)?(?:\.(\d+))?([b-gijostTuvxX])/,key:/^([a-z_][a-z_\d]*)/i,key_access:/^\.([a-z_][a-z_\d]*)/i,index_access:/^\[(\d+)\]/,sign:/^[+-]/},t=Object.create(null)})()})();
