var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(e,m,k){e instanceof String&&(e=String(e));for(var h=e.length,n=0;n<h;n++){var q=e[n];if(m.call(k,q,n,e))return{i:n,v:q}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(e,m,k){e!=Array.prototype&&e!=Object.prototype&&(e[m]=k.value)};
$jscomp.getGlobal=function(e){return"undefined"!=typeof window&&window===e?e:"undefined"!=typeof global&&null!=global?global:e};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(e,m,k,h){if(m){k=$jscomp.global;e=e.split(".");for(h=0;h<e.length-1;h++){var n=e[h];n in k||(k[n]={});k=k[n]}e=e[e.length-1];h=k[e];m=m(h);m!=h&&null!=m&&$jscomp.defineProperty(k,e,{configurable:!0,writable:!0,value:m})}};
$jscomp.polyfill("Array.prototype.find",function(e){return e?e:function(e,k){return $jscomp.findInternal(this,e,k).v}},"es6","es3");
(function(){function e(a,b,c,d,f){b=void 0===b?null:b;d=void 0===d?!1:d;f=void 0===f?null:f;null===b&&(b="");null===f&&(f={});if(f.noTagsIfNoContent&&!b)return b;c=m(a,void 0===c?null:c,d);if(d)return c;p(b)?b[0]=c+b[0]:b=c+b;c=k(a);p(b)?b[b.length-1]+=c:b+=c;return b}function m(a,b,c){c=void 0===c?!1:c;if(!a)return"";b=void 0===b?null:b;var d="";if(p(b))for(var f in b){var g=b[f];if(void 0!==g){d+=" "+f+'="';if(p(g))if("style"==f)for(var l in g)d+=l+":"+g[l]+";";else{var e=!0;for(l=0;l<g.length;l++)e||
(d+=" "),d+=g[l],e=!1}else d+=w(g,!1,'"');d+='"'}}else"string"===typeof b&&(d+=" "+b);return"<"+a+d+(c?" /":"")+">"}function k(a){return a?"</"+a+">":""}function h(a,b,c,d,f,g,e){c=void 0===c?!1:c;d=void 0===d?!1:d;f=void 0===f?null:f;g=void 0===g?null:g;e=void 0===e?null:e;p(e)||(e={});b&&(e.id=b);return n("checkbox",a,e,null,c,d,f,g)}function n(a,b,c,d,f,g,l,h){d=void 0===d?null:d;f=void 0===f?!1:f;g=void 0===g?!1:g;l=void 0===l?null:l;h=void 0===h?null:h;var n="";p(c)||(c={});h&&(p(l)||(l={}),
c.title=l.title=h);h="";if(p(b)){var t=b;b="";for(var u in t)if(p(u)){t="";var q=null;isset(u[2])&&(q=u[2]);var v=u[0];b+='<a href="#" id="'+v+'_view" onclick="var ctl = document.getElementById( \''+v+"' ); var iNew = ctl.selectedIndex + 1; if( iNew >= ctl.options.length ) iNew = 0; if( ctl.selectedIndex != iNew ) { ctl.selectedIndex = iNew; ctl.onchange(); } return false;\">";for(var r in u[1])isset(r[2])&&r[2]&&(q=r[0]),t+='<option value="'+r[0]+'"',q==r[0]&&(b+=r[1],t+=" selected"),t+=">"+r[1]+
"</option>";b+="</a>";h+='<select id="'+v+'"'+(g?' name="'+v+'"':"")+' style="display: none;"';h+=" onchange=\"var text = this.selectedIndex >= 0 ? this.options[ this.selectedIndex ].text : ''; document.getElementById( '"+v+"_view' ).text = text;\">";h+=t;h+="</select>"}else b+=u}n+=m("label",l);l=c.id;c.type=a;g&&l&&(c.name=l);d&&(c.value=d);f&&(c.checked="checked");n+=e("input",null,c,!0);return n+=b+h+k("label")}function q(a,b,c){c=void 0===c?!1:c;if(!a||!a.length)return"";b=""+m("ul",void 0===
b?null:b);for(var d=0;d<a.length;d++){var f=a[d];b+=m("li");b+=h(f.name,f.id,!1,c,null,null,{onchange:"cryptocurrency_prices.Ui._cb.CheckBoxTree_OnChange(this)"});f.items&&(b+=q(f.items,null,c));b+=k("li")}return b+=k("ul")}function x(a){a=jQuery("#cryptocurrency_prices_popup_"+a);1==a.attr("attr-modal")&&jQuery(".cryptocurrency_prices.popup_modal_overlay").hide();a.hide()}function w(a,b,c){b=void 0===b?!1:b;c=void 0===c?null:c;if("string"!==typeof a)return a;a=cryptocurrency_prices.Gen.StrReplaceAll(a,
"&","&amp;");'"'===c&&(a=cryptocurrency_prices.Gen.StrReplaceAll(a,'"',"&quot;"));"'"===c&&(a=cryptocurrency_prices.Gen.StrReplaceAll(a,"'","&#039;"));a=cryptocurrency_prices.Gen.StrReplaceAll(a,"<","&lt;");a=cryptocurrency_prices.Gen.StrReplaceAll(a,">","&gt;");b&&(a=cryptocurrency_prices.Gen.StrReplaceAll(a," ","&nbsp;"));return a}function p(a){return a&&"object"===typeof a}function y(a,b){var c=!b.children().length;a.find(".items-list-empty-content").toggle(c);b.toggle(!c)}cryptocurrency_prices.Ui=
{EscHtml:w,HtmlToPlainText:function(a){var b=document.createElement("div");b.innerHTML=a;return b.textContent||b.innerText||""},Text:function(a){return"string"!==typeof a?"":a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")},Comment:function(a){"string"!==typeof a&&(a="");return"\x3c!-- "+a+" --\x3e"},Tag:e,TagOpen:m,TagClose:k,Link:function(a,b,c,d,f){c=void 0===c?!1:c;d=void 0===d?null:d;f=void 0===f?null:f;null===f&&(f={});null===d&&(d={});if(b){var g="",e=d.linkPreContent;e&&(g+=
e);f.href=b;c&&0!==b.indexOf("mailto:")&&(f.target="_blank");g+=m("a",f);p(a)?a[0]=g+a[0]:a=g+a}else if(d.noTextIfNoHref){if(!p(a))return"";a[0]="";a[a.length-1]="";3==a.length&&(a[1]="");return a}b&&(g=k("a"),(b=d.linkAfterContent)&&(g+=b),p(a)?a[a.length-1]+=g:a+=g);return a},Button:function(a,b,c,d,f,g){b=void 0===b?!1:b;c=void 0===c?null:c;d=void 0===d?null:d;f=void 0===f?"submit":f;g=void 0===g?null:g;var l="button"==f&&-1!==a.indexOf("<");g||(g={});c&&(g.name=c);l||(g.type=f,g.value=a,a=null);
Array.isArray(g.class)||(g.class=[]);g.class.push("button");b&&g.class.push("button-primary");d&&(Array.isArray(d)?g.class=g.class.concat(d):g.class.push(d));return e(l?"button":"input",a,g)},CheckBox:h,RadioBox:function(a,b,c,d,f,g,e){d=void 0===d?!1:d;f=void 0===f?null:f;g=void 0===g?null:g;e=void 0===e?null:e;p(e)||(e={});b&&(e.name=b);return n("radio",a,e,c,d,f,g)},CheckBoxTree:function(a,b,c){b=void 0===b?null:b;c=void 0===c?!1:c;p(b)||(b={});b.class=["cryptocurrency_prices_CheckBoxTree"];return q(a,
b,c)},LogItem:function(a,b,c){var d="dashicons-info",f="clrWpInfo";switch(a){case "success":d="dashicons-info";f="clrWpSucc";break;case "warning":d="dashicons-warning";f="clrWpWarn";break;case "error":d="dashicons-warning",f="clrWpErr"}if(void 0===c||c)a=b.slice(-1),"."!=a&&"?"!=a&&(b+=".");return e("div",e("div",null,{"class":"icon dashicons "+d+" "+f})+e("div",b,{"class":"text"}),{"class":"logItem"})},PopupShow:function(a){var b=jQuery("#cryptocurrency_prices_popup_"+a),c=1==b.attr("attr-modal"),
d=b.attr("attr-body");d&&(b.removeAttr("attr-body"),b.html(decodeURIComponent(d)));c&&(jQuery(".cryptocurrency_prices.popup_modal_overlay").show(),jQuery(document).bind("keyup",function(b){if("Escape"===b.key)return x(a),!1}));b.show()},PopupClose:x,ItemsList:{_Init:function(a,b,c,d,f){a=jQuery(a).find("ul.items-list");a.length&&(a[0]._ItemsListCtx={onItemDel:b,nextItemId:c,contentNewItem:d},f&&(a.sortable({placeholder:"ui-sortable-placeholder",forcePlaceholderSize:!0}),a.disableSelection()))},AddItem:function(a,
b){a=jQuery(b).closest(a);b=a.find("ul.items-list");b.length&&(b.append(b[0]._ItemsListCtx.contentNewItem.replace(/{{itemId}}/g,b[0]._ItemsListCtx.nextItemId)),b[0]._ItemsListCtx.nextItemId++,a.find(".items-list-empty-content").hide(),b.show())},MoveItem:function(a,b,c){jQuery(b).closest(a).find("ul.items-list").length&&(a=jQuery(b).closest("li.item"),0<c?(c=a.next(),c.length&&a.insertAfter(c)):0>c&&(c=a.prev(),c.length&&a.insertBefore(c)))},DelItem:function(a,b){a=jQuery(b).closest(a);var c=a.find("ul.items-list");
if(c.length){b=jQuery(b).closest("li.item");var d=c[0]._ItemsListCtx.onItemDel;d&&d(a,c,b);b.remove();y(a,c)}},DelAllItems:function(a,b){var c=jQuery(b).closest(a),d=c.find("ul.items-list");d.length&&(d.children().each(function(){var a=jQuery(this),b=d[0]._ItemsListCtx.onItemDel;b&&b(c,d,a);a.remove()}),y(c,d))}},_cb:{CheckBoxTree_OnChange:function(a){function b(a){var d=a.parent().parent(),e=!0;a.siblings().each(function(){return e=jQuery(this).children("label").find('input[type="checkbox"]').prop("checked")===
c});e&&c?(d.children("label").find('input[type="checkbox"]').prop({indeterminate:!1,checked:c}),b(d)):e&&!c?(d.children("label").find('input[type="checkbox"]').prop("checked",c),d.children("label").find('input[type="checkbox"]').prop("indeterminate",0<d.find('input[type="checkbox"]:checked').length),b(d)):a.parents("li").children("label").find('input[type="checkbox"]').prop({indeterminate:!0,checked:!1})}var c=jQuery(a).prop("checked");a=jQuery(a).parent().parent();a.find('input[type="checkbox"]').prop({indeterminate:!1,
checked:c});b(a)}}}})();
