var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(b){var f=0;return function(){return f<b.length?{done:!1,value:b[f++]}:{done:!0}}};$jscomp.arrayIterator=function(b){return{next:$jscomp.arrayIteratorImpl(b)}};$jscomp.makeIterator=function(b){var f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];return f?f.call(b):$jscomp.arrayIterator(b)};
$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,f,g){b!=Array.prototype&&b!=Object.prototype&&(b[f]=g.value)};
$jscomp.polyfill=function(b,f,g,k){if(f){g=$jscomp.global;b=b.split(".");for(k=0;k<b.length-1;k++){var c=b[k];c in g||(g[c]={});g=g[c]}b=b[b.length-1];k=g[b];f=f(k);f!=k&&null!=f&&$jscomp.defineProperty(g,b,{configurable:!0,writable:!0,value:f})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(b){function f(){this.batch_=null}function g(a){return a instanceof c?a:new c(function(h,b){h(a)})}if(b&&!$jscomp.FORCE_POLYFILL_PROMISE)return b;f.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};f.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var k=$jscomp.global.setTimeout;f.prototype.asyncExecuteFunction=function(a){k(a,
0)};f.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var h=0;h<a.length;++h){var b=a[h];a[h]=null;try{b()}catch(v){this.asyncThrow_(v)}}}this.batch_=null};f.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var c=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(x){b.reject(x)}};c.prototype.createResolveAndReject_=
function(){function a(a){return function(h){c||(c=!0,a.call(b,h))}}var b=this,c=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};c.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof c)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};c.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(x){this.reject_(x);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};c.prototype.reject_=function(a){this.settle_(2,a)};c.prototype.fulfill_=function(a){this.settle_(1,a)};c.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};c.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
0;a<this.onSettledCallbacks_.length;++a)m.asyncExecute(this.onSettledCallbacks_[a]);this.onSettledCallbacks_=null}};var m=new f;c.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};c.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(v){c.reject(v)}};c.prototype.then=function(b,f){function a(b,a){return"function"==typeof b?function(a){try{h(b(a))}catch(y){g(y)}}:
a}var h,g,k=new c(function(b,a){h=b;g=a});this.callWhenSettled_(a(b,h),a(f,g));return k};c.prototype.catch=function(b){return this.then(void 0,b)};c.prototype.callWhenSettled_=function(b,c){function a(){switch(f.state_){case 1:b(f.result_);break;case 2:c(f.result_);break;default:throw Error("Unexpected state: "+f.state_);}}var f=this;null==this.onSettledCallbacks_?m.asyncExecute(a):this.onSettledCallbacks_.push(a)};c.resolve=g;c.reject=function(b){return new c(function(a,c){c(b)})};c.race=function(b){return new c(function(a,
c){for(var f=$jscomp.makeIterator(b),h=f.next();!h.done;h=f.next())g(h.value).callWhenSettled_(a,c)})};c.all=function(b){var a=$jscomp.makeIterator(b),f=a.next();return f.done?g([]):new c(function(b,c){function h(a){return function(c){k[a]=c;m--;0==m&&b(k)}}var k=[],m=0;do k.push(void 0),m++,g(f.value).callWhenSettled_(h(k.length-1),c),f=a.next();while(!f.done)})};return c},"es6","es3");
var regeneratorRuntime=function(b){function f(d,l,b,a){l=Object.create((l&&l.prototype instanceof k?l:k).prototype);a=new C(a||[]);l._invoke=x(d,b,a);return l}function g(d,l,b){try{return{type:"normal",arg:d.call(l,b)}}catch(J){return{type:"throw",arg:J}}}function k(){}function c(){}function m(){}function a(d){["next","throw","return"].forEach(function(l){d[l]=function(d){return this._invoke(l,d)}})}function h(d){function l(b,a,n,c){b=g(d[b],d,a);if("throw"===b.type)c(b.arg);else{var e=b.arg;return(b=
e.value)&&"object"===typeof b&&r.call(b,"__await")?Promise.resolve(b.__await).then(function(b){l("next",b,n,c)},function(b){l("throw",b,n,c)}):Promise.resolve(b).then(function(b){e.value=b;n(e)},function(b){return l("throw",b,n,c)})}}var b;this._invoke=function(d,a){function n(){return new Promise(function(b,n){l(d,a,b,n)})}return b=b?b.then(n,n):n()}}function x(b,l,a){var d=G;return function(e,c){if(d===H)throw Error("Generator is already running");if(d===z){if("throw"===e)throw c;return F()}a.method=
e;for(a.arg=c;;){if(e=a.delegate)if(e=v(e,a)){if(e===p)continue;return e}if("next"===a.method)a.sent=a._sent=a.arg;else if("throw"===a.method){if(d===G)throw d=z,a.arg;a.dispatchException(a.arg)}else"return"===a.method&&a.abrupt("return",a.arg);d=H;e=g(b,l,a);if("normal"===e.type){d=a.done?z:K;if(e.arg===p)continue;return{value:e.arg,done:a.done}}"throw"===e.type&&(d=z,a.method="throw",a.arg=e.arg)}}}function v(b,a){var d=b.iterator[a.method];if(d===q){a.delegate=null;if("throw"===a.method){if(b.iterator.return&&
(a.method="return",a.arg=q,v(b,a),"throw"===a.method))return p;a.method="throw";a.arg=new TypeError("The iterator does not provide a 'throw' method")}return p}d=g(d,b.iterator,a.arg);if("throw"===d.type)return a.method="throw",a.arg=d.arg,a.delegate=null,p;d=d.arg;if(!d)return a.method="throw",a.arg=new TypeError("iterator result is not an object"),a.delegate=null,p;if(d.done)a[b.resultName]=d.value,a.next=b.nextLoc,"return"!==a.method&&(a.method="next",a.arg=q);else return d;a.delegate=null;return p}
function I(a){var b={tryLoc:a[0]};1 in a&&(b.catchLoc=a[1]);2 in a&&(b.finallyLoc=a[2],b.afterLoc=a[3]);this.tryEntries.push(b)}function E(a){var b=a.completion||{};b.type="normal";delete b.arg;a.completion=b}function C(a){this.tryEntries=[{tryLoc:"root"}];a.forEach(I,this);this.reset(!0)}function D(a){if(a){var b=a[A];if(b)return b.call(a);if("function"===typeof a.next)return a;if(!isNaN(a.length)){var d=-1;b=function e(){for(;++d<a.length;)if(r.call(a,d))return e.value=a[d],e.done=!1,e;e.value=
q;e.done=!0;return e};return b.next=b}}return{next:F}}function F(){return{value:q,done:!0}}var y=Object.prototype,r=y.hasOwnProperty,q,t="function"===typeof Symbol?Symbol:{},A=t.iterator||"@@iterator",L=t.asyncIterator||"@@asyncIterator",B=t.toStringTag||"@@toStringTag";b.wrap=f;var G="suspendedStart",K="suspendedYield",H="executing",z="completed",p={};t={};t[A]=function(){return this};var u=Object.getPrototypeOf;(u=u&&u(u(D([]))))&&u!==y&&r.call(u,A)&&(t=u);var w=m.prototype=k.prototype=Object.create(t);
c.prototype=w.constructor=m;m.constructor=c;m[B]=c.displayName="GeneratorFunction";b.isGeneratorFunction=function(a){return(a="function"===typeof a&&a.constructor)?a===c||"GeneratorFunction"===(a.displayName||a.name):!1};b.mark=function(a){Object.setPrototypeOf?Object.setPrototypeOf(a,m):(a.__proto__=m,B in a||(a[B]="GeneratorFunction"));a.prototype=Object.create(w);return a};b.awrap=function(a){return{__await:a}};a(h.prototype);h.prototype[L]=function(){return this};b.AsyncIterator=h;b.async=function(a,
c,n,g){var d=new h(f(a,c,n,g));return b.isGeneratorFunction(c)?d:d.next().then(function(a){return a.done?a.value:d.next()})};a(w);w[B]="Generator";w[A]=function(){return this};w.toString=function(){return"[object Generator]"};b.keys=function(a){var b=[],d;for(d in a)b.push(d);b.reverse();return function e(){for(;b.length;){var d=b.pop();if(d in a)return e.value=d,e.done=!1,e}e.done=!0;return e}};b.values=D;C.prototype={constructor:C,reset:function(a){this.next=this.prev=0;this.sent=this._sent=q;this.done=
!1;this.delegate=null;this.method="next";this.arg=q;this.tryEntries.forEach(E);if(!a)for(var b in this)"t"===b.charAt(0)&&r.call(this,b)&&!isNaN(+b.slice(1))&&(this[b]=q)},stop:function(){this.done=!0;var a=this.tryEntries[0].completion;if("throw"===a.type)throw a.arg;return this.rval},dispatchException:function(a){function b(b,c){f.type="throw";f.arg=a;d.next=b;c&&(d.method="next",d.arg=q);return!!c}if(this.done)throw a;for(var d=this,c=this.tryEntries.length-1;0<=c;--c){var e=this.tryEntries[c],
f=e.completion;if("root"===e.tryLoc)return b("end");if(e.tryLoc<=this.prev){var g=r.call(e,"catchLoc"),h=r.call(e,"finallyLoc");if(g&&h){if(this.prev<e.catchLoc)return b(e.catchLoc,!0);if(this.prev<e.finallyLoc)return b(e.finallyLoc)}else if(g){if(this.prev<e.catchLoc)return b(e.catchLoc,!0)}else if(h){if(this.prev<e.finallyLoc)return b(e.finallyLoc)}else throw Error("try statement without catch or finally");}}},abrupt:function(a,b){for(var c=this.tryEntries.length-1;0<=c;--c){var d=this.tryEntries[c];
if(d.tryLoc<=this.prev&&r.call(d,"finallyLoc")&&this.prev<d.finallyLoc){var e=d;break}}e&&("break"===a||"continue"===a)&&e.tryLoc<=b&&b<=e.finallyLoc&&(e=null);c=e?e.completion:{};c.type=a;c.arg=b;return e?(this.method="next",this.next=e.finallyLoc,p):this.complete(c)},complete:function(a,b){if("throw"===a.type)throw a.arg;"break"===a.type||"continue"===a.type?this.next=a.arg:"return"===a.type?(this.rval=this.arg=a.arg,this.method="return",this.next="end"):"normal"===a.type&&b&&(this.next=b);return p},
finish:function(a){for(var b=this.tryEntries.length-1;0<=b;--b){var c=this.tryEntries[b];if(c.finallyLoc===a)return this.complete(c.completion,c.afterLoc),E(c),p}},"catch":function(a){for(var b=this.tryEntries.length-1;0<=b;--b){var c=this.tryEntries[b];if(c.tryLoc===a){a=c.completion;if("throw"===a.type){var d=a.arg;E(c)}return d}}throw Error("illegal catch attempt");},delegateYield:function(a,b,c){this.delegate={iterator:D(a),resultName:b,nextLoc:c};"next"===this.method&&(this.arg=q);return p}};
return b}("object"===typeof module?module.exports:{});
